# Font
font_size 14.0
font_family Mononoki Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

background 0x2e3436
foreground 0xd3d7cf
background_opacity 0.95

cursor #fcfcfa
cursor_text_color #000000
selection_foreground #403e41
selection_background #fcfcfa

# dull black
color0 0x2e3436
# light black
color8 0x555753

# dull red
color1 0xcc0000
# light red
color9 0xef2929

# dull green
color2 0x4e9a06
# light green
color10 0x8ae234

# yellow
color3 0xc4a000
# light yellow
color11 0xfce94f

# blue
color4 0x3465a4
# light blue
color12 0x729fcf

# magenta
color5 0x75507b
# light magenta
color13 0xad7fa8

# cyan
color6 0x06989a
# light cyan
color14 0x34e2e2

# dull white
color7 0xd3d7cf
# bright white
color15 0xeeeeec
